// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "DNSecure",
    platforms: [
        .iOS("16.1")
    ],
    products: [
        .iOSApplication(
            name: "DNSecure",
            targets: ["DNSecure"],
            bundleIdentifier: "xyz.kebo.DNSecure",
            teamIdentifier: "X4678G5DL2",
            displayVersion: "1.5.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "DNSecure",
            path: "DNSecure"
        ),
        .testTarget(
            name: "DNSecureTests",
            dependencies: [
                "DNSecure"
            ],
            path: "DNSecureTests"
        ),
    ]
)
