name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: {}
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    container: swift:6.2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - run: swift format lint -rsp .
  yamllint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - run: yamllint --version
      - run: yamllint --strict --config-file .yamllint.yml .
