name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: {}
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    container: swift:6.3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: swift format lint -rsp .
  yamllint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: yamllint --version
      - run: yamllint --strict --config-file .yamllint.yml .
